### ISSUE TITLE
'Calendar' object has no attribute 'to_ical'

### ISSUE THREAD

**Issue by kroeliebuschie** [kroeliebuschie/AstroCalendar#2]
```
Traceback (most recent call last):
  File "getAstroCal.py", line 144, in <module>
    main()
  File "getAstroCal.py", line 141, in main
    saveIcal(cal)
  File "getAstroCal.py", line 63, in saveIcal
    ical_handle.write(cal.to_ical())
AttributeError: 'Calendar' object has no attribute 'to_ical'
```

**Comment by kroeliebuschie** [comment]
probably an issue with icalendar 2 vs icalendar 3 (`to_string` vs `to_ical`)
